CC=gcc

all: pthreads_selection_sort

pthreads_selection_sort: pthreads_selection_sort.c
	$(CC) pthreads_selection_sort.c -o pthreads_selection_sort -lm -lpthread

clean:
	rm -rf pthreads_selection_sort
